# yaml-language-server: $schema=https://json.schemastore.org/golangci-lint.json
# https://golangci-lint.run/usage/configuration/
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  goimports:
    local-prefixes: github.com/peterldowns/panoctocon
  govet:
    enable-all: true
    disable:
      - fieldalignment
  exhaustive:
    default-signifies-exhaustive: true
  nolintlint:
    allow-unused: false
    allow-no-explanation:
      - gochecknoglobals
      - gochecknoinits
      - unparam
    require-explanation: true
    require-specific: true
  # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
  revive:
    enable-all-rules: false
    rules:
      - name: atomic
      #- name: blank-imports
      - name: bare-return
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: comment-spacings
        arguments: ["nolint"]
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T"
      - name: context-keys-type
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: function-result-limit
        arguments: [3]
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: imports-blacklist
        arguments: []
      - name: import-shadowing
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: package-comments
      - name: range
      - name: range-val-address
      - name: range-val-in-closure
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-format
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
        arguments:
          - "fmt.*"
          - "strings.Builder.WriteString"
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: use-any
      - name: useless-break
      - name: var-declaration
      - name: waitgroup-by-value
run:
  tests: true
  timeout: 1m
  args:
    - "--skip-dirs-use-default"
    - "."
  dirs:
    - "."

# https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - exhaustive
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - govet
    - ineffassign
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace
    - paralleltest
    - errname
    - errorlint
    - gosimple
    - unparam
issues:
  exclude:
    # Allow shadowing of `err` because it's so common
    - 'declaration of "err" shadows declaration at'
  max-same-issues: 10000
  max-issues-per-linter: 10000
  exclude-dirs:
    - pkg/database/models
