linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  goimports:
    local-prefixes: github.com/peterldowns/localias
  govet:
    enable-all: true
    disable:
      - fieldalignment
  exhaustive:
    default-signifies-exhaustive: true
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    allow-no-explanation: [depguard, gochecknoglobals, gochecknoinits]
    require-explanation: true
    require-specific: true
  # golint is deprecated. The recommended replacement is revive, which is a drop-in replacement
  # for golint with additional rules and configuration options. For a list of available rules and
  # configurations, see https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md.
  # Rules below that are commented out require some minor refactoring before they can be enabled.
  revive:
    rules:
      - name: atomic
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
      # - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      # - name: deep-exit
      # - name: defer
      #   arguments: [[call-chain, loop, method-call, recover]]
      - name: dot-imports
      - name: duplicated-imports
      # - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      # - name: flag-parameter
      # - name: get-return
      - name: identical-branches
      # - name: if-return
      # - name: import-shadowing
      - name: imports-blacklist
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: package-comments
      - name: range
      - name: range-val-address
      - name: range-val-in-closure
      - name: receiver-naming
      - name: string-format
      - name: string-of-int
      - name: struct-tag
      # - name: superfluous-else
      - name: time-naming
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      # - name: unused-receiver
      - name: var-declaration
      - name: var-naming
      - name: waitgroup-by-value
run:
  tests: true
  timeout: 1m
linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - errorlint
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unparam
    - unused
    - whitespace
issues:
  exclude:
    # Allow shadowing of `err` because it's so common
    - 'declaration of "err" shadows declaration at'
  max-same-issues: 10000
  max-issues-per-linter: 10000
