name: golang
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: go.sum
      - name: build
        run: go build -v ./...
      - name: test
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
    # https://github.com/golangci/golangci-lint-action#annotations
    permissions:
      contents: read # read the repo
      pull-requests: read # allows the 'only-new-issues' option to work
      checks: write # annotate code in the PR
    steps:
      - uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          install-mode: "binary"
          version: "v2.0.2" # matches `golangci-lint --version` in nix devshell
          # the default behavior as of v7.0.0:
          verify: true
      - name: go mod tidy
        run: go mod tidy
      - name: assert no changed files
        run: ./scripts/check-for-differences.sh
